import {
  User,
  Subject,
  Chapter,
  Topic,
  Question,
  SafeQuestion,
  ExamSet,
  ExamAttempt,
  LearnerAnswer,
  MistakeItem,
  TopicMastery,
  SubjectMastery,
  Tutor,
  TutorBooking,
  ContentVersion,
  AuditLog,
  DailyStudyPlan,
  LiveClass,
} from '../types/index.js';

export class DatabaseStore {
  public users: User[] = [
    {
      id: 'usr_istihad',
      email: 'istihadahmed1163@gmail.com',
      name: 'Istihad Ahmed',
      phone: '+8801700000000',
      role: 'STUDENT',
      subscription: 'PRO',
      studentProfile: {
        academicLevel: 'HSC & University Admission',
        educationBoard: 'Dhaka Board',
        subjects: ['Higher Mathematics', 'Physics', 'Chemistry'],
        targetExam: 'BUET & University Admission',
        preferredLanguage: 'bn',
        studyGoal: 'Comprehensive preparation for HSC & Competitive Engineering Entrance Tests',
        dailyStudyHours: 4.5,
      },
      targetExam: 'BUET & University Admission',
      targetBatch: 'HSC 2025 Batch',
      examCountdownDays: 14,
      targetScore: 95,
      preferredLanguage: 'bn',
      dailyGoalHours: 4.5,
      currentStreakDays: 14,
      highestStreakDays: 21,
      institution: 'Academic Student',
      createdAt: '2024-01-10T08:00:00.000Z',
    },
  ];

  // Active current user session pointer
  public currentUserId = 'usr_istihad';

  // Configurable Education Boards (stored in database)
  public educationBoards: string[] = [
    'Dhaka Board',
    'Chittagong Board',
    'Rajshahi Board',
    'Dinajpur Board',
    'Comilla Board',
    'Sylhet Board',
    'Barisal Board',
    'Jessore Board',
    'Mymensingh Board',
    'Madrasah Education Board',
    'Bangladesh Technical Education Board',
    'Cambridge / Edexcel International',
  ];

  // Live Online Classes
  public liveClasses: LiveClass[] = [];

  // 8 Core Bangladesh Subjects
  public subjects: Subject[] = [
    {
      id: 'sub_physics',
      nameEn: 'Physics',
      nameBn: 'পদার্থবিজ্ঞান',
      code: 'PHY-101',
      color: '#D97706',
      icon: 'bolt',
      description: 'Mechanics, Thermodynamics, Electricity, Magnetism & Wave Optics for HSC & Admission.',
      topicsCount: 16,
      status: 'PUBLISHED',
    },
    {
      id: 'sub_math',
      nameEn: 'Higher Mathematics',
      nameBn: 'উচ্চতর গণিত',
      code: 'HMATH-102',
      color: '#4F46E5',
      icon: 'functions',
      description: 'Calculus, Vectors, Matrix & Determinants, Trigonometry, Coordinate Geometry.',
      topicsCount: 18,
      status: 'PUBLISHED',
    },
    {
      id: 'sub_chem',
      nameEn: 'Chemistry',
      nameBn: 'রসায়ন',
      code: 'CHEM-103',
      color: '#059669',
      icon: 'science',
      description: 'Organic Reactions, Electrochemistry, Chemical Kinetics, Qualitative Analysis.',
      topicsCount: 14,
      status: 'PUBLISHED',
    },
    {
      id: 'sub_bio',
      nameEn: 'Biology',
      nameBn: 'জীববিজ্ঞান',
      code: 'BIO-104',
      color: '#E11D48',
      icon: 'genetics',
      description: 'Genetics, Molecular Biology, Human Physiology, Botany for HSC & Medical Admission.',
      topicsCount: 15,
      status: 'PUBLISHED',
    },
    {
      id: 'sub_bangla',
      nameEn: 'Bangla',
      nameBn: 'বাংলা',
      code: 'BNG-105',
      color: '#EA580C',
      icon: 'menu_book',
      description: 'Bangla Grammar (ব্যাকরণ), Literature (সাহিত্য), Comprehension for HSC, DU KHA & BCS.',
      topicsCount: 12,
      status: 'PUBLISHED',
    },
    {
      id: 'sub_english',
      nameEn: 'English',
      nameBn: 'ইংরেজি',
      code: 'ENG-106',
      color: '#0284C7',
      icon: 'translate',
      description: 'Advanced Grammar, Vocabulary, Reading Comprehension, Prepositions & Sentence Correction.',
      topicsCount: 14,
      status: 'PUBLISHED',
    },
    {
      id: 'sub_ict',
      nameEn: 'ICT',
      nameBn: 'তথ্য ও যোগাযোগ প্রযুক্তি',
      code: 'ICT-107',
      color: '#7C3AED',
      icon: 'code',
      description: 'Number Systems, Digital Logic, HTML, C Programming, Database Management (SQL).',
      topicsCount: 11,
      status: 'PUBLISHED',
    },
    {
      id: 'sub_gk',
      nameEn: 'General Knowledge',
      nameBn: 'সাধারণ জ্ঞান',
      code: 'GK-108',
      color: '#0D9488',
      icon: 'public',
      description: 'Bangladesh Affairs, Liberation War 1971, Constitution, International Geopolitics.',
      topicsCount: 16,
      status: 'PUBLISHED',
    },
  ];

  public chapters: Chapter[] = [
    { id: 'ch_calc', subjectId: 'sub_math', nameEn: 'Calculus & Integration', nameBn: 'ক্যালকুলাস ও যোগজীকরণ', chapterNumber: 9, status: 'PUBLISHED' },
    { id: 'ch_matrix', subjectId: 'sub_math', nameEn: 'Matrices and Determinants', nameBn: 'ম্যাট্রিক্স ও নির্ণায়ক', chapterNumber: 1, status: 'PUBLISHED' },
    { id: 'ch_trig', subjectId: 'sub_math', nameEn: 'Trigonometry', nameBn: 'ত্রিকোণমিতি', chapterNumber: 6, status: 'PUBLISHED' },
    { id: 'ch_thermo', subjectId: 'sub_physics', nameEn: 'Thermodynamics', nameBn: 'তাপগতিবিদ্যা', chapterNumber: 1, status: 'PUBLISHED' },
    { id: 'ch_mechanics', subjectId: 'sub_physics', nameEn: 'Dynamics & Kinematics', nameBn: 'গতিবিদ্যা ও নিউটনিয়ান বলবিদ্যা', chapterNumber: 3, status: 'PUBLISHED' },
    { id: 'ch_organic', subjectId: 'sub_chem', nameEn: 'Organic Chemistry', nameBn: 'জৈব রসায়ন', chapterNumber: 2, status: 'PUBLISHED' },
    { id: 'ch_genetics', subjectId: 'sub_bio', nameEn: 'Genetics and Evolution', nameBn: 'জিনতত্ত্ব ও বিবর্তন', chapterNumber: 11, status: 'PUBLISHED' },
    { id: 'ch_bangla_gram', subjectId: 'sub_bangla', nameEn: 'Bangla Grammar & Syntax', nameBn: 'বাংলা ব্যাকরণ ও বাক্যতত্ত্ব', chapterNumber: 1, status: 'PUBLISHED' },
    { id: 'ch_eng_gram', subjectId: 'sub_english', nameEn: 'Advanced English Grammar', nameBn: 'ইংরেজি ব্যাকরণ ও প্রিপজিশন', chapterNumber: 2, status: 'PUBLISHED' },
    { id: 'ch_ict_prog', subjectId: 'sub_ict', nameEn: 'C Programming & Logic', nameBn: 'সি প্রোগ্রামিং ও ডিজিটাল লজিক', chapterNumber: 5, status: 'PUBLISHED' },
    { id: 'ch_gk_bd', subjectId: 'sub_gk', nameEn: 'Bangladesh Affairs & 1971 History', nameBn: 'বাংলাদেশ বিষয়াবলী ও মুক্তিযুদ্ধ', chapterNumber: 1, status: 'PUBLISHED' },
  ];

  public topics: Topic[] = [
    { id: 'top_int_parts', chapterId: 'ch_calc', subjectId: 'sub_math', nameEn: 'Integration by Parts & Partial Fractions', nameBn: 'আংশিক ভগ্নাংশ ও অংশে অংশে যোগজীকরণ', code: 'MATH-CALC-01', importance: 5, status: 'PUBLISHED' },
    { id: 'top_limits', chapterId: 'ch_calc', subjectId: 'sub_math', nameEn: 'Trigonometric Limits & L’Hôpital', nameBn: 'ত্রিকোণমিতিক লিমিট ও এল হসপিটাল নিয়ম', code: 'MATH-CALC-02', importance: 4, status: 'PUBLISHED' },
    { id: 'top_thermo_iso', chapterId: 'ch_thermo', subjectId: 'sub_physics', nameEn: 'Isothermal & Adiabatic Gas Processes', nameBn: 'সমোষ্ণ ও রুদ্ধতাপীয় গ্যাস প্রক্রিয়া', code: 'PHY-THERM-01', importance: 5, status: 'PUBLISHED' },
    { id: 'top_projectile', chapterId: 'ch_mechanics', subjectId: 'sub_physics', nameEn: 'Kinematics & Projectile Dynamics', nameBn: 'প্রক্ষেপক ও প্রাস সংক্রান্ত গতিবিদ্যা', code: 'PHY-MECH-01', importance: 5, status: 'PUBLISHED' },
    { id: 'top_organic_rxn', chapterId: 'ch_organic', subjectId: 'sub_chem', nameEn: 'Electrophilic Substitution & Benzene', nameBn: 'ইলেকট্রোফিলিক প্রতিস্থাপন ও বেনজিন বিক্রিয়া', code: 'CHEM-ORG-01', importance: 5, status: 'PUBLISHED' },
    { id: 'top_genetics_mendel', chapterId: 'ch_genetics', subjectId: 'sub_bio', nameEn: 'Mendelian Genetics & Blood Groups', nameBn: 'মেন্ডেলের সূত্র ও রক্তের গ্রুপ', code: 'BIO-GEN-01', importance: 4, status: 'PUBLISHED' },
    { id: 'top_bng_shobdo', chapterId: 'ch_bangla_gram', subjectId: 'sub_bangla', nameEn: 'Bangla Sandhi & Samas (সন্ধি ও সমাস)', nameBn: 'সন্ধি ও সমাস নির্ণয়', code: 'BNG-GRAM-01', importance: 4, status: 'PUBLISHED' },
    { id: 'top_eng_prep', chapterId: 'ch_eng_gram', subjectId: 'sub_english', nameEn: 'Appropriate Prepositions & Subject-Verb Agreement', nameBn: 'এপ্রোপ্রিয়েট প্রিপজিশন ও সাবজেক্ট-ভার্ব এগ্রিমেন্ট', code: 'ENG-GRAM-01', importance: 5, status: 'PUBLISHED' },
    { id: 'top_ict_c', chapterId: 'ch_ict_prog', subjectId: 'sub_ict', nameEn: 'C Programming Loops & Arrays', nameBn: 'সি প্রোগ্রামিং লুপ ও অ্যারে', code: 'ICT-PROG-01', importance: 4, status: 'PUBLISHED' },
    { id: 'top_gk_1971', chapterId: 'ch_gk_bd', subjectId: 'sub_gk', nameEn: '1971 Liberation War Sectors & Commanders', nameBn: 'মুক্তিযুদ্ধের সেক্টর ও সেক্টর কমান্ডারগণ', code: 'GK-BD-01', importance: 5, status: 'PUBLISHED' },
  ];

  // Normalized Questions database supporting Bilingual content and protected on server
  public questions: Question[] = [
    {
      id: 14,
      subjectId: 'sub_math',
      subjectName: 'Higher Mathematics',
      chapterId: 'ch_calc',
      chapterName: 'Calculus & Integration',
      topicId: 'top_int_parts',
      topicName: 'Integration by Parts & Partial Fractions',
      difficulty: 'Hard',
      titleEn: 'Rational Polynomial Partial Fraction Integration',
      titleBn: 'আংশিক ভগ্নাংশে মূলদ বহুপদী সমাকলন',
      questionTextEn: 'Evaluate the indefinite integral:',
      questionTextBn: 'অনির্দিষ্ট যোগজটির মান নির্ণয় করো:',
      formula: '∫ (3x² + 2x + 1) / (x³ + x² + x + 1) dx',
      graphType: 'integral',
      options: [
        { id: 'A', textEn: 'ln|x³ + x² + x + 1| + C', textBn: 'ln|x³ + x² + x + 1| + C' },
        { id: 'B', textEn: '(3x² + 2x + 1) ln|x| + C', textBn: '(3x² + 2x + 1) ln|x| + C' },
        { id: 'C', textEn: 'ln|x + 1| + ln(x² + 1) + C', textBn: 'ln|x + 1| + ln(x² + 1) + C' },
        { id: 'D', textEn: 'arctan(x) + ln|x + 1| + C', textBn: 'arctan(x) + ln|x + 1| + C' },
      ],
      correctOptionId: 'C',
      explanation: {
        overviewEn: 'Factoring the denominator reveals grouped linear and quadratic factors: x³ + x² + x + 1 = (x² + 1)(x + 1).',
        overviewBn: 'হরটিকে উৎপাদকে বিশ্লেষণ করলে পাওয়া যায় (x² + 1)(x + 1)।',
        whyWrongDetailsEn: 'Choosing Option A happens when misidentifying numerator as the exact derivative of denominator, neglecting that partial fraction decomposition splits the integrand into 1/(x+1) + 2x/(x²+1).',
        whyWrongDetailsBn: 'অপশন A পছন্দ করা একটি সাধারণ ভুল যখন শিক্ষার্থী হরটির অন্তর্কলজের সাথে তুলনা না করে সরাসরি লগারিদম প্রয়োগের চেষ্টা করে।',
        stepByStepEn: [
          '1. Factor denominator: x²(x + 1) + 1(x + 1) = (x² + 1)(x + 1).',
          '2. Express in partial fractions: (3x² + 2x + 1)/[(x² + 1)(x + 1)] = 1/(x + 1) + 2x/(x² + 1).',
          '3. Integrate term by term: ∫ 1/(x + 1) dx + ∫ 2x/(x² + 1) dx = ln|x + 1| + ln(x² + 1) + C.',
        ],
        stepByStepBn: [
          '১. হরটিকে উৎপাদকে বিশ্লেষণ করি: x²(x + 1) + 1(x + 1) = (x² + 1)(x + 1)।',
          '২. আংশিক ভগ্নাংশে রূপান্তর: 1/(x + 1) + 2x/(x² + 1)।',
          '৩. পদভিত্তিক সমাকলন: ∫ 1/(x + 1) dx + ∫ 2x/(x² + 1) dx = ln|x + 1| + ln(x² + 1) + C।',
        ],
        simpleExplanationEn: 'Separate into (x+1) and (x²+1). The integral splits into 1/(x+1) yielding ln|x+1|, and 2x/(x²+1) yielding ln(x²+1).',
        simpleExplanationBn: 'হরকে দুটি সরল অংশে ভাগ করে প্রতিটির জন্য আলাদাভাবে সমাকলন সমাধান করুন।',
        keyTakeawayEn: 'Always factor polynomial denominators first before attempting logarithmic forms.',
        keyTakeawayBn: 'যোগজীকরণের পূর্বে বহুপদী হরকে অবশ্যই উৎপাদকে বিশ্লেষণ করে নিন।',
      },
      defaultMistakeCategory: 'Conceptual Error',
      curriculum: 'HSC',
      board: 'Dhaka Board',
      admissionCategory: 'BUET / Engineering',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-15T10:00:00.000Z',
      updatedAt: '2024-01-15T10:00:00.000Z',
      publishedAt: '2024-01-15T10:00:00.000Z',
    },
    {
      id: 17,
      subjectId: 'sub_physics',
      subjectName: 'Physics',
      chapterId: 'ch_thermo',
      chapterName: 'Thermodynamics',
      topicId: 'top_thermo_iso',
      topicName: 'Isothermal & Adiabatic Gas Processes',
      difficulty: 'Medium',
      titleEn: 'Ideal Gas Isothermal Expansion',
      titleBn: 'আদর্শ গ্যাসের সমোষ্ণ প্রসারণ',
      questionTextEn: 'An ideal gas in a cylinder undergoes an isothermal expansion from volume V₁ to V₂ (where V₂ = 2V₁). Which statement correctly describes the change in internal energy (ΔU) and heat absorbed (Q)?',
      questionTextBn: 'একটি আবদ্ধ সিলিন্ডারে থাকা আদর্শ গ্যাস সমোষ্ণ প্রক্রিয়ায় আয়তন V₁ থেকে V₂ (যেখানে V₂ = 2V₁) তে প্রসারিত হলো। অভ্যন্তরীণ শক্তির পরিবর্তন (ΔU) এবং শোষিত তাপ (Q) সম্পর্কে কোনটি সত্য?',
      formula: 'ΔU = Q - W',
      graphType: 'thermodynamics',
      options: [
        { id: 'A', textEn: 'ΔU = 0 and Q > 0', textBn: 'ΔU = 0 এবং Q > 0' },
        { id: 'B', textEn: 'ΔU > 0 and Q = 0', textBn: 'ΔU > 0 এবং Q = 0' },
        { id: 'C', textEn: 'ΔU < 0 and Q < 0', textBn: 'ΔU < 0 এবং Q < 0' },
        { id: 'D', textEn: 'ΔU = 0 and Q < 0', textBn: 'ΔU = 0 এবং Q < 0' },
      ],
      correctOptionId: 'A',
      explanation: {
        overviewEn: 'In an isothermal process for an ideal gas, temperature remains strictly constant (ΔT = 0), so ΔU = 0. As the gas expands doing positive work (W > 0), heat Q must enter the system (Q = W > 0).',
        overviewBn: 'আদর্শ গ্যাসের ক্ষেত্রে সমোষ্ণ প্রক্রিয়ায় তাপমাত্রা ধ্রুব থাকায় অভ্যন্তরীণ শক্তির পরিবর্তন শূন্য হয় (ΔU = 0)। প্রসারণে কাজ পজিটিভ হওয়ায় তাপগতিবিদ্যার প্রথম সূত্র মতে শোষিত তাপ Q > 0 হতে হবে।',
        whyWrongDetailsEn: 'Assuming adiabatic condition (Q = 0) is a common trap, but in isothermal conditions temperature is preserved via heat transfer.',
        whyWrongDetailsBn: 'রুদ্ধতাপীয় প্রক্রিয়ার সাথে গুলিয়ে ফেলে Q = 0 ধারণা করা একটি সাধারণ ভ্রান্তি।',
        stepByStepEn: [
          '1. Internal energy of ideal gas is solely a function of temperature: ΔT = 0 ⇒ ΔU = 0.',
          '2. Work done in expansion: W = nRT ln(V₂/V₁) > 0 since V₂ = 2V₁ > V₁.',
          '3. 1st Law of Thermodynamics: ΔU = Q - W ⇒ 0 = Q - W ⇒ Q = W > 0.',
        ],
        stepByStepBn: [
          '১. আদর্শ গ্যাসের অভ্যন্তরীণ শক্তি শুধুমাত্র তাপমাত্রার উপর নির্ভরশীল: ΔT = 0 হলে ΔU = 0।',
          '২. প্রসারণে কৃতকাজ: W = nRT ln(2) > 0।',
          '৩. তাপগতিবিদ্যার ১ম সূত্র: ΔU = Q - W ⇒ Q = W > 0।',
        ],
        simpleExplanationEn: 'Since temperature stays constant, internal energy change is zero. The gas expands and does work, so heat must flow in from outside.',
        simpleExplanationBn: 'তাপমাত্রা অপরিবর্তিত থাকায় অভ্যন্তরীণ শক্তি বাড়ে বা কমে না। তবে প্রসারণের কাজের জন্য বাইরে থেকে তাপ গ্রহণ আবশ্যক।',
        keyTakeawayEn: 'Isothermal ideal gas always has ΔU = 0; expansion requires positive heat intake (Q > 0).',
        keyTakeawayBn: 'সমোষ্ণ আদর্শ গ্যাসে সর্বদা ΔU = 0 এবং প্রসারণে Q > 0।',
      },
      defaultMistakeCategory: 'Conceptual Error',
      curriculum: 'HSC',
      board: 'All Board',
      admissionCategory: 'BUET / Engineering',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-16T10:00:00.000Z',
      updatedAt: '2024-01-16T10:00:00.000Z',
      publishedAt: '2024-01-16T10:00:00.000Z',
    },
    {
      id: 1,
      subjectId: 'sub_physics',
      subjectName: 'Physics',
      chapterId: 'ch_mechanics',
      chapterName: 'Dynamics & Kinematics',
      topicId: 'top_projectile',
      topicName: 'Kinematics & Projectile Dynamics',
      difficulty: 'Medium',
      titleEn: 'Maximum Projectile Range on Flat Ground',
      titleBn: 'সমতল ভূমিতে প্রক্ষেপকের সর্বাধিক পাল্লা',
      questionTextEn: 'A projectile is launched with initial velocity v₀ at an angle θ relative to the horizontal. Neglecting air drag, which angle maximizes horizontal range R?',
      questionTextBn: 'ভূ-পৃষ্ঠ থেকে v₀ আদিবেগে এবং অনুভূমিকের সাথে θ কোণে একটি প্রক্ষেপক নিক্ষেপ করা হলো। বায়ু প্রতিরোধ অগ্রাহ্য করলে কোন কোণে অনুভূমিক পাল্লা (R) সর্বাধিক হবে?',
      formula: 'R = (v₀² sin 2θ) / g',
      options: [
        { id: 'A', textEn: '30°', textBn: '30°' },
        { id: 'B', textEn: '45°', textBn: '45°' },
        { id: 'C', textEn: '60°', textBn: '60°' },
        { id: 'D', textEn: '90°', textBn: '90°' },
      ],
      correctOptionId: 'B',
      explanation: {
        overviewEn: 'Range R is proportional to sin(2θ). The maximum of sin(2θ) is 1, which occurs when 2θ = 90°, hence θ = 45°.',
        overviewBn: 'অনুভূমিক পাল্লা R = (v₀² sin 2θ) / g। sin(2θ) এর মান সর্বোচ্চ ১ হলে পাল্লা সর্বাধিক হয়, অর্থাৎ 2θ = 90° বা θ = 45°।',
        stepByStepEn: [
          '1. Range formula: R = (v₀² sin 2θ) / g.',
          '2. Maximize sin(2θ) = 1.',
          '3. 2θ = 90° ⇒ θ = 45°.',
        ],
        stepByStepBn: [
          '১. পাল্লার সূত্র: R = (v₀² sin 2θ) / g।',
          '২. sin(2θ) এর সর্বোচ্চ মান = ১।',
          '৩. 2θ = 90° হলে θ = 45°।',
        ],
        simpleExplanationEn: '45 degrees provides the ideal balance between flight time and horizontal velocity.',
        simpleExplanationBn: '৪৫ ডিগ্রি কোণ উড্ডয়নকাল এবং অনুভূমিক বেগের সর্বোত্তম সমন্বয় নিশ্চিত করে।',
        keyTakeawayEn: 'Maximum level ground range is attained strictly at θ = 45°.',
        keyTakeawayBn: 'সমতল পৃষ্ঠে প্রক্ষেপকের সর্বোচ্চ পাল্লার জন্য নিক্ষেপণ কোণ ৪৫°।',
      },
      defaultMistakeCategory: 'Calculation Error',
      curriculum: 'HSC',
      board: 'Dhaka Board',
      admissionCategory: 'Medical / DMC',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-17T10:00:00.000Z',
      updatedAt: '2024-01-17T10:00:00.000Z',
      publishedAt: '2024-01-17T10:00:00.000Z',
    },
    {
      id: 201,
      subjectId: 'sub_chem',
      subjectName: 'Chemistry',
      chapterId: 'ch_organic',
      chapterName: 'Organic Chemistry',
      topicId: 'top_organic_rxn',
      topicName: 'Electrophilic Substitution & Benzene',
      difficulty: 'Medium',
      titleEn: 'Nitration of Benzene Mechanism',
      titleBn: 'বেনজিনের নাইট্রেশন বিক্রিয়া ও ইলেকট্রোফাইল',
      questionTextEn: 'In the nitration of benzene using concentrated HNO₃ and concentrated H₂SO₄ at 50°C-60°C, what acts as the active electrophile?',
      questionTextBn: 'গাঢ় HNO₃ এবং গাঢ় H₂SO₄ এর মিশ্রণে ৫০°C-৬০°C তাপমাত্রায় বেনজিনের নাইট্রেশন বিক্রিয়ায় সক্রিয় ইলেকট্রোফাইল কোনটি?',
      formula: 'HNO₃ + 2H₂SO₄ ⇌ NO₂⁺ + H₃O⁺ + 2HSO₄⁻',
      options: [
        { id: 'A', textEn: 'NO₂⁺ (Nitronium ion)', textBn: 'NO₂⁺ (নাইট্রোনিয়াম আয়ন)' },
        { id: 'B', textEn: 'NO₃⁻ (Nitrate ion)', textBn: 'NO₃⁻ (নাইট্রেট আয়ন)' },
        { id: 'C', textEn: 'HNO₂ (Nitrous acid)', textBn: 'HNO₂ (নাইট্রাস এসিড)' },
        { id: 'D', textEn: 'NO⁺ (Nitrosonium ion)', textBn: 'NO⁺ (নাইট্রোসোনিয়াম আয়ন)' },
      ],
      correctOptionId: 'A',
      explanation: {
        overviewEn: 'Concentrated sulfuric acid protonates nitric acid, generating the powerful electrophile nitronium ion (NO₂⁺).',
        overviewBn: 'গাঢ় সালফিউরিক এসিড নাইট্রিক এসিডকে প্রোটোনেটেড করে সক্রিয় ইলেকট্রোফাইল নাইট্রোনিয়াম আয়ন (NO₂⁺) তৈরি করে।',
        stepByStepEn: [
          '1. H₂SO₄ acts as stronger acid: HNO₃ + H₂SO₄ → H₂NO₃⁺ + HSO₄⁻.',
          '2. Dehydration yields nitronium ion: H₂NO₃⁺ → NO₂⁺ + H₂O.',
          '3. Electrophile NO₂⁺ attacks electron-rich pi cloud of benzene.',
        ],
        stepByStepBn: [
          '১. H₂SO₄ তীব্র এসিড হিসেবে প্রোটন দান করে: HNO₃ + H₂SO₄ → H₂NO₃⁺ + HSO₄⁻।',
          '২. পানি অপসারিত হয়ে নাইট্রোনিয়াম আয়ন গঠিত হয়: H₂NO₃⁺ → NO₂⁺ + H₂O।',
          '৩. সক্রিয় ইলেকট্রোফাইল NO₂⁺ বেনজিন বলয়ে আক্রমণ করে।',
        ],
        simpleExplanationEn: 'The nitronium ion NO₂⁺ is positive and seeks the negative pi electrons of benzene.',
        simpleExplanationBn: 'ধনাত্মক নাইট্রোনিয়াম আয়ন NO₂⁺ বেনজিনের পাই ইলেকট্রনের প্রতি আকৃষ্ট হয়ে আক্রমণ করে।',
        keyTakeawayEn: 'Active electrophile for benzene nitration is strictly NO₂⁺.',
        keyTakeawayBn: 'বেনজিন নাইট্রেশনের সক্রিয় ইলেকট্রোফাইল হলো NO₂⁺।',
      },
      defaultMistakeCategory: 'Formula Error',
      curriculum: 'HSC',
      board: 'Rajshahi Board',
      admissionCategory: 'Medical / DMC',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-18T10:00:00.000Z',
      updatedAt: '2024-01-18T10:00:00.000Z',
      publishedAt: '2024-01-18T10:00:00.000Z',
    },
    {
      id: 301,
      subjectId: 'sub_bio',
      subjectName: 'Biology',
      chapterId: 'ch_genetics',
      chapterName: 'Genetics and Evolution',
      topicId: 'top_genetics_mendel',
      topicName: 'Mendelian Genetics & Blood Groups',
      difficulty: 'Easy',
      titleEn: 'ABO Blood Group Universal Donor & Recipient',
      titleBn: 'ABO রক্ত গ্রুপ: সর্বজনীন দাতা ও গ্রহীতা',
      questionTextEn: 'Which blood group is known as the universal donor in the human ABO blood grouping system due to the absence of A and B antigens on red blood cells?',
      questionTextBn: 'লোহিত রক্ত কণিকায় A ও B অ্যান্টিজেন অনুপস্থিত থাকার কারণে মানবদেহের ABO ব্লাড গ্রুপে কোন গ্রুপকে "সর্বজনীন দাতা" (Universal Donor) বলা হয়?',
      options: [
        { id: 'A', textEn: 'Blood Group AB (Rh-)', textBn: 'ব্লাড গ্রুপ AB (Rh-)' },
        { id: 'B', textEn: 'Blood Group O (Rh-)', textBn: 'ব্লাড গ্রুপ O (Rh-)' },
        { id: 'C', textEn: 'Blood Group A (Rh+)', textBn: 'ব্লাড গ্রুপ A (Rh+)' },
        { id: 'D', textEn: 'Blood Group B (Rh-)', textBn: 'ব্লাড গ্রুপ B (Rh-)' },
      ],
      correctOptionId: 'B',
      explanation: {
        overviewEn: 'Blood group O negative contains neither A nor B antigens on RBC membranes, making it safe for transfusion across all blood groups.',
        overviewBn: 'O নেগেটিভ রক্তে লোহিত রক্ত কণিকায় কোনো A বা B অ্যান্টিজেন এবং Rh অ্যান্টিজেন থাকে না, তাই এটি সর্বজনীন দাতা।',
        stepByStepEn: [
          '1. O blood group has no A or B antigens on RBC surface.',
          '2. Rh-negative has no D antigen.',
          '3. Recipient antibodies will not agglutinate transfused O- cells.',
        ],
        stepByStepBn: [
          '১. O গ্রুপের লোহিত কণিকায় কোনো A বা B অ্যান্টিজেন থাকে না।',
          '২. Rh- এ D অ্যান্টিজেন থাকে না।',
          '৩. গ্রহীতার অ্যান্টিবডি কোনো জমাটবদ্ধতা (Agglutination) তৈরি করে না।',
        ],
        simpleExplanationEn: 'Type O negative has no trigger antigens, so any recipient body accepts it safely.',
        simpleExplanationBn: 'O নেগেটিভ রক্তে কোনো অ্যান্টিজেন না থাকায় গ্রহীতার ইমিউন সিস্টেম বাধা দেয় না।',
        keyTakeawayEn: 'Group O- is universal donor; Group AB+ is universal recipient.',
        keyTakeawayBn: 'O নেগেটিভ সর্বজনীন দাতা এবং AB পজিটিভ সর্বজনীন গ্রহীতা।',
      },
      defaultMistakeCategory: 'Careless Mistake',
      curriculum: 'HSC',
      board: 'Chittagong Board',
      admissionCategory: 'Medical / DMC',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-19T10:00:00.000Z',
      updatedAt: '2024-01-19T10:00:00.000Z',
      publishedAt: '2024-01-19T10:00:00.000Z',
    },
    {
      id: 401,
      subjectId: 'sub_bangla',
      subjectName: 'Bangla',
      chapterId: 'ch_bangla_gram',
      chapterName: 'Bangla Grammar & Syntax',
      topicId: 'top_bng_shobdo',
      topicName: 'Bangla Sandhi & Samas (সন্ধি ও সমাস)',
      difficulty: 'Medium',
      titleEn: 'Bangla Grammar Samas Identification',
      titleBn: 'বাংলা ব্যাকরণ: সমাস নির্ণয়',
      questionTextEn: 'Identify the classification of Samas for the word "পীতাম্বর" (পীত অম্বর যার):',
      questionTextBn: '"পীতাম্বর" (পীত অম্বর যার) পদটি কোন সমাসের উদাহরণ?',
      options: [
        { id: 'A', textEn: 'Tatpurush Samas (তৎপুরুষ সমাস)', textBn: 'তৎপুরুষ সমাস' },
        { id: 'B', textEn: 'Bahubrihi Samas (বহুব্রীহি সমাস)', textBn: 'বহুব্রীহি সমাস' },
        { id: 'C', textEn: 'Karmadharaya Samas (কর্মধারয় সমাস)', textBn: 'কর্মধারয় সমাস' },
        { id: 'D', textEn: 'Dvandva Samas (দ্বন্দ্ব সমাস)', textBn: 'দ্বন্দ্ব সমাস' },
      ],
      correctOptionId: 'B',
      explanation: {
        overviewEn: '"পীতাম্বর" does not mean yellow cloth literally, but refers to Sri Krishna/Vishnu. When neither component word retains primary meaning and indicates a third entity, it is Bahubrihi Samas.',
        overviewBn: 'যে সমাসে পূর্বপদ বা পরপদ কোনোটির অর্থ না বুঝিয়ে ভিন্ন কোনো তৃতীয় অর্থ (এখানে শ্রীকৃষ্ণ) প্রকাশ পায়, তাকে বহুব্রীহি সমাস বলে।',
        stepByStepEn: [
          '1. ব্যাসবাক্য: পীত অম্বর যার = পীতাম্বর।',
          '2. পীত (হলুদ) এবং অম্বর (বস্ত্র) কোনোটিই প্রধান নয়।',
          '3. তৃতীয় বিশেষ ব্যক্তি নির্দেশ করায় এটি সমানাধিকরণ বহুব্রীহি সমাস।',
        ],
        stepByStepBn: [
          '১. ব্যাসবাক্য: পীত অম্বর যার = পীতাম্বর।',
          '২. পীত (হলুদ) বা অম্বর (বস্ত্র) মূল অর্থ নয়।',
          '৩. তৃতীয় অর্থ প্রকাশ করায় এটি বহুব্রীহি সমাস।',
        ],
        simpleExplanationEn: 'When the compound word points to a completely different subject, it is Bahubrihi.',
        simpleExplanationBn: 'পূর্বপদ বা পরপদের অর্থ না বুঝিয়ে অন্য অর্থ বোঝালে তা বহুব্রীহি সমাস হয়।',
        keyTakeawayEn: 'পীতাম্বর is an iconic example of Bahubrihi Samas in BCS & University admission.',
        keyTakeawayBn: 'পীতাম্বর (পীত অম্বর যার) সমানাধিকরণ বহুব্রীহি সমাস।',
      },
      defaultMistakeCategory: 'Conceptual Error',
      curriculum: 'Admission',
      board: 'All Board',
      admissionCategory: 'Dhaka University (KA/KHA)',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-20T10:00:00.000Z',
      updatedAt: '2024-01-20T10:00:00.000Z',
      publishedAt: '2024-01-20T10:00:00.000Z',
    },
    {
      id: 501,
      subjectId: 'sub_english',
      subjectName: 'English',
      chapterId: 'ch_eng_gram',
      chapterName: 'Advanced English Grammar',
      topicId: 'top_eng_prep',
      topicName: 'Appropriate Prepositions & Subject-Verb Agreement',
      difficulty: 'Medium',
      titleEn: 'Appropriate Preposition with "Abide"',
      titleBn: 'Appropriate Preposition: Abide',
      questionTextEn: 'Fill in the blank with the appropriate preposition: "A student must abide _____ the institutional code of conduct."',
      questionTextBn: 'উপযুক্ত প্রিপজিশন দিয়ে শূন্যস্থান পূরণ করো: "A student must abide _____ the institutional code of conduct."',
      options: [
        { id: 'A', textEn: 'with', textBn: 'with' },
        { id: 'B', textEn: 'by', textBn: 'by' },
        { id: 'C', textEn: 'to', textBn: 'to' },
        { id: 'D', textEn: 'for', textBn: 'for' },
      ],
      correctOptionId: 'B',
      explanation: {
        overviewEn: 'The phrasal verb "abide by" means to accept, conform to, or obey a rule, decision, or law.',
        overviewBn: '"Abide by" একটি বহুল ব্যবহৃত এপ্রোপ্রিয়েট প্রিপজিশন যার অর্থ কোনো নিয়ম বা সিদ্ধান্ত মেনে চলা।',
        stepByStepEn: [
          '1. "Abide by" = to follow/obey a rule or decision.',
          '2. "Abide with" is obsolete or used poetically for staying with someone.',
          '3. Therefore, "abide by" is the correct standard usage.',
        ],
        stepByStepBn: [
          '১. "Abide by" মানে কোনো আইন বা নিয়ম মেনে চলা।',
          '২. বাক্যে "code of conduct" (নিয়মাবলী) উল্লেখ থাকায় "by" প্রযোজ্য।',
        ],
        simpleExplanationEn: 'Always use "by" after "abide" when talking about rules and laws.',
        simpleExplanationBn: 'নিয়মকানুন মেনে চলার ক্ষেত্রে "abide" এর সাথে সর্বদা "by" ব্যবহৃত হয়।',
        keyTakeawayEn: 'Abide by = obey a rule/regulation.',
        keyTakeawayBn: 'Abide by অর্থ কোনো আইন বা নিয়ম মান্য করা।',
      },
      defaultMistakeCategory: 'Formula Error',
      curriculum: 'HSC',
      board: 'Dhaka Board',
      admissionCategory: 'Dhaka University (KA/KHA)',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-21T10:00:00.000Z',
      updatedAt: '2024-01-21T10:00:00.000Z',
      publishedAt: '2024-01-21T10:00:00.000Z',
    },
    {
      id: 601,
      subjectId: 'sub_ict',
      subjectName: 'ICT',
      chapterId: 'ch_ict_prog',
      chapterName: 'C Programming & Logic',
      topicId: 'top_ict_c',
      topicName: 'C Programming Loops & Arrays',
      difficulty: 'Medium',
      titleEn: 'C Programming Post-Increment Loop Count',
      titleBn: 'সি প্রোগ্রামিং পোস্ট-ইনক্রিমেন্ট লুপ গণনা',
      questionTextEn: 'How many times will the following C loop execute?\n\nint i = 0;\nwhile (i++ < 5) {\n    // code\n}',
      questionTextBn: 'নিচের সি প্রোগ্রামিং লুপটি কতবার আবর্তিত (execute) হবে?\n\nint i = 0;\nwhile (i++ < 5) {\n    // code\n}',
      options: [
        { id: 'A', textEn: '4 times', textBn: '৪ বার' },
        { id: 'B', textEn: '5 times', textBn: '৫ বার' },
        { id: 'C', textEn: '6 times', textBn: '৬ বার' },
        { id: 'D', textEn: 'Infinite loop', textBn: 'অসীম বার' },
      ],
      correctOptionId: 'B',
      explanation: {
        overviewEn: 'In post-increment (i++ < 5), the comparison is evaluated with the initial value of i (0, 1, 2, 3, 4), and then i is incremented. It executes exactly 5 times.',
        overviewBn: 'পোস্ট-ইনক্রিমেন্টে শর্ত যাচাইয়ের সময় i এর মান যথাক্রমে 0, 1, 2, 3, 4 থাকে যা ৫-এর চেয়ে ছোট। ফলে লুপটি ঠিক ৫ বার চলবে।',
        stepByStepEn: [
          'Iteration 1: i=0 (0<5 true) -> i becomes 1 -> body runs',
          'Iteration 2: i=1 (1<5 true) -> i becomes 2 -> body runs',
          'Iteration 3: i=2 (2<5 true) -> i becomes 3 -> body runs',
          'Iteration 4: i=3 (3<5 true) -> i becomes 4 -> body runs',
          'Iteration 5: i=4 (4<5 true) -> i becomes 5 -> body runs',
          'Iteration 6: i=5 (5<5 false) -> i becomes 6 -> loop terminates.',
        ],
        stepByStepBn: [
          '১ম বার: i=0 (0<5 সত্য) -> লুপ চলবে',
          '২য় বার: i=1 (1<5 সত্য) -> লুপ চলবে',
          '৩য় বার: i=2 (2<5 সত্য) -> লুপ চলবে',
          '৪র্থ বার: i=3 (3<5 সত্য) -> লুপ চলবে',
          '৫ম বার: i=4 (4<5 সত্য) -> লুপ চলবে',
          '৬ষ্ঠ বার: i=5 (5<5 মিথ্যা) -> লুপ সমাপ্ত।',
        ],
        simpleExplanationEn: 'The numbers 0, 1, 2, 3, and 4 each trigger a successful loop cycle, totaling 5 executions.',
        simpleExplanationBn: '০ থেকে ৪ পর্যন্ত মোট ৫টি মানের জন্য শর্ত সত্য হয়, তাই লুপটি ৫ বার চলবে।',
        keyTakeawayEn: 'Post-increment checks first, then increments.',
        keyTakeawayBn: 'পোস্ট-ইনক্রিমেন্টে আগে মান পরীক্ষা হয় এবং পরে মান বৃদ্ধি পায়।',
      },
      defaultMistakeCategory: 'Calculation Error',
      curriculum: 'HSC',
      board: 'Dhaka Board',
      admissionCategory: 'BUET / Engineering',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-22T10:00:00.000Z',
      updatedAt: '2024-01-22T10:00:00.000Z',
      publishedAt: '2024-01-22T10:00:00.000Z',
    },
    {
      id: 701,
      subjectId: 'sub_gk',
      subjectName: 'General Knowledge',
      chapterId: 'ch_gk_bd',
      chapterName: 'Bangladesh Affairs & 1971 History',
      topicId: 'top_gk_1971',
      topicName: '1971 Liberation War Sectors & Commanders',
      difficulty: 'Easy',
      titleEn: '1971 Liberation War Sector Without Regular Commander',
      titleBn: '১৯৭১ সালের মুক্তিযুদ্ধের ব্যতিক্রমী নৌ-সেক্টর',
      questionTextEn: 'During the 1971 Bangladesh Liberation War, which sector operated as the naval commando sector without a single designated regular sector commander?',
      questionTextBn: '১৯৭১ সালের মহান মুক্তিযুদ্ধে কোন সেক্টরটি নৌ-কমান্ডো সেক্টর হিসেবে পরিচালিত হয়েছিল এবং যার কোনো স্থায়ী নিয়মিত সেক্টর কমান্ডার ছিলেন না?',
      options: [
        { id: 'A', textEn: 'Sector 2 (সেক্টর ২)', textBn: 'সেক্টর ২' },
        { id: 'B', textEn: 'Sector 7 (সেক্টর ৭)', textBn: 'সেক্টর ৭' },
        { id: 'C', textEn: 'Sector 10 (সেক্টর ১০)', textBn: 'সেক্টর ১০' },
        { id: 'D', textEn: 'Sector 11 (সেক্টর ১১)', textBn: 'সেক্টর ১১' },
      ],
      correctOptionId: 'C',
      explanation: {
        overviewEn: 'Sector 10 was the naval commando sector covering internal riverine and coastal waters. Naval commandos were deployed across different sectors as needed and reported directly to HQ without a static resident commander.',
        overviewBn: 'সেক্টর ১০ ছিল মুক্তিযুদ্ধের নৌ-সেক্টর। এই সেক্টরের আওতায় কোনো ভৌগোলিক এলাকা নির্দিষ্ট ছিল না এবং কোনো স্থায়ী সেক্টর কমান্ডার ছিলেন না; এটি সরাসরি সি-ইন-সি হেডকোয়ার্টার দ্বারা পরিচালিত হতো (অপারেশন জ্যাকপট)।',
        stepByStepEn: [
          '1. Bangladesh was partitioned into 11 military sectors in July 1971.',
          '2. Sector 10 comprised the naval commandos and inland waterways.',
          '3. Famous Operation Jackpot was executed under Sector 10.',
        ],
        stepByStepBn: [
          '১. ১৯৭১ সালের জুলাই মাসে সমগ্র দেশকে ১১টি সেক্টরে ভাগ করা হয়।',
          '২. সেক্টর ১০ ছিল নৌ কমান্ডোদের জন্য নির্ধারিত।',
          '৩. ঐতিহাসিক "অপারেশন জ্যাকপট" এই সেক্টরের কমান্ডোদের দ্বারা সংঘটিত হয়।',
        ],
        simpleExplanationEn: 'Sector 10 was the waterborne force that operated throughout rivers without a fixed regional commander.',
        simpleExplanationBn: 'সেক্টর ১০ ছিল একটি ব্যতিক্রমী নৌ সেক্টর যার কোনো একক নিয়মিত সেক্টর কমান্ডার ছিলেন না।',
        keyTakeawayEn: 'Sector 10 = Naval Commando sector with no regular resident commander.',
        keyTakeawayBn: 'সেক্টর ১০: নিয়মিত সেক্টর কমান্ডারবিহীন নৌ-সেক্টর।',
      },
      defaultMistakeCategory: 'Careless Mistake',
      curriculum: 'Admission',
      board: 'All Board',
      admissionCategory: 'BCS',
      status: 'PUBLISHED',
      version: 1,
      createdBy: 'usr_admin_1',
      reviewedBy: 'usr_admin_1',
      publishedBy: 'usr_admin_1',
      createdAt: '2024-01-23T10:00:00.000Z',
      updatedAt: '2024-01-23T10:00:00.000Z',
      publishedAt: '2024-01-23T10:00:00.000Z',
    },
    // Draft question to test review & publishing workflow
    {
      id: 801,
      subjectId: 'sub_math',
      subjectName: 'Higher Mathematics',
      chapterId: 'ch_calc',
      chapterName: 'Calculus & Integration',
      topicId: 'top_limits',
      topicName: 'Trigonometric Limits & L’Hôpital',
      difficulty: 'Medium',
      titleEn: 'Standard Trigonometric Limit Evaluation',
      titleBn: 'ত্রিকোণমিতিক আদর্শ লিমিট নির্ণয়',
      questionTextEn: 'Evaluate the limit as x approaches 0: lim (x→0) [sin(5x) / tan(2x)]',
      questionTextBn: 'মান নির্ণয় করো: lim (x→0) [sin(5x) / tan(2x)]',
      formula: 'lim (x→0) [sin(ax)/tan(bx)] = a/b',
      options: [
        { id: 'A', textEn: '2/5', textBn: '২/৫' },
        { id: 'B', textEn: '5/2', textBn: '৫/২' },
        { id: 'C', textEn: '1', textBn: '১' },
        { id: 'D', textEn: '0', textBn: '০' },
      ],
      correctOptionId: 'B',
      explanation: {
        overviewEn: 'Using standard limit forms lim(x->0) sin(ax)/ax = 1 and lim(x->0) tan(bx)/bx = 1 gives (5/2).',
        overviewBn: 'আদর্শ লিমিট সূত্র প্রয়োগে ফলাফল ৫/২ হয়।',
        stepByStepEn: ['1. Multiply and divide by 5x and 2x.', '2. (5/2) * [sin(5x)/5x] / [tan(2x)/2x] = 5/2.'],
        stepByStepBn: ['১. ৫x এবং ২x দ্বারা লব ও হরকে গুণ করে সাজাই।', '২. মান দাঁড়ায় ৫/২।'],
        simpleExplanationEn: 'The ratio of coefficients 5 over 2 gives the direct answer.',
        simpleExplanationBn: 'সহগদ্বয়ের অনুপাত ৫/২ সরাসরি উত্তর নির্দেশ করে।',
        keyTakeawayEn: 'lim (x->0) sin(ax)/tan(bx) = a/b.',
        keyTakeawayBn: 'lim (x->0) sin(ax)/tan(bx) = a/b।',
      },
      defaultMistakeCategory: 'Calculation Error',
      curriculum: 'HSC',
      board: 'Dhaka Board',
      admissionCategory: 'BUET / Engineering',
      status: 'DRAFT', // Admin can review and publish
      version: 1,
      createdBy: 'usr_admin_1',
      createdAt: '2024-02-01T10:00:00.000Z',
      updatedAt: '2024-02-01T10:00:00.000Z',
    },
  ];

  // Exam Sets (Published and managed on server)
  public examSets: ExamSet[] = [
    {
      id: 'exam_buet_math',
      titleEn: 'Comprehensive Higher Mathematics Engineering Mock #4',
      titleBn: 'বুয়েট ও ইঞ্জিনিয়ারিং উচ্চতর গণিত পূর্ণাঙ্গ মডেল টেস্ট #৪',
      subjectId: 'sub_math',
      subjectName: 'Higher Mathematics',
      totalQuestions: 20,
      durationMinutes: 45,
      isFullMock: true,
      targetCategory: 'BUET / Engineering',
      questionIds: [14, 801, 1, 17, 201, 601],
      status: 'PUBLISHED',
      publishedAt: '2024-01-15T00:00:00.000Z',
    },
    {
      id: 'exam_physics_comprehensive',
      titleEn: 'Physics Paper 1 & 2 Comprehensive Mock Test',
      titleBn: 'পদার্থবিজ্ঞান ১ম ও ২য় পত্র সমন্বিত মডেল টেস্ট',
      subjectId: 'sub_physics',
      subjectName: 'Physics',
      totalQuestions: 20,
      durationMinutes: 40,
      isFullMock: true,
      targetCategory: 'Medical / BUET Admission',
      questionIds: [17, 1, 601, 701, 14, 201],
      status: 'PUBLISHED',
      publishedAt: '2024-01-16T00:00:00.000Z',
    },
    {
      id: 'exam_medical_bio',
      titleEn: 'Medical Admission Biology & Chemistry Super Drill',
      titleBn: 'মেডিকেল ভর্তি পরীক্ষা: জীববিজ্ঞান ও রসায়ন সুপার ড্রিল',
      subjectId: 'sub_bio',
      subjectName: 'Biology',
      totalQuestions: 20,
      durationMinutes: 30,
      isFullMock: true,
      targetCategory: 'Medical / DMC',
      questionIds: [301, 201, 701, 501, 17, 1],
      status: 'PUBLISHED',
      publishedAt: '2024-01-17T00:00:00.000Z',
    },
  ];

  // Exam attempts store (server-authoritative)
  public examAttempts: ExamAttempt[] = [];

  // Learner answers store
  public learnerAnswers: LearnerAnswer[] = [];

  // Student mistakes ledger
  public mistakes: MistakeItem[] = [
    {
      id: 'mstk_001',
      userId: 'usr_istihad',
      questionId: 14,
      category: 'Conceptual Error',
      studentAnswer: 'B',
      correctAnswer: 'C',
      attemptCount: 2,
      correctCount: 0,
      lastAttempted: new Date().toISOString(),
      isResolved: false,
      notes: 'Factored the denominator incorrectly; missed linear and quadratic grouping.',
      question: null as any, // populated in query
    },
    {
      id: 'mstk_002',
      userId: 'usr_istihad',
      questionId: 201,
      category: 'Formula Error',
      studentAnswer: 'B',
      correctAnswer: 'A',
      attemptCount: 1,
      correctCount: 0,
      lastAttempted: new Date().toISOString(),
      isResolved: false,
      notes: 'Confused nitrate ion NO₃⁻ with electrophile nitronium ion NO₂⁺.',
      question: null as any,
    },
    {
      id: 'mstk_003',
      userId: 'usr_istihad',
      questionId: 601,
      category: 'Calculation Error',
      studentAnswer: 'A',
      correctAnswer: 'B',
      attemptCount: 1,
      correctCount: 0,
      lastAttempted: new Date().toISOString(),
      isResolved: false,
      notes: 'Miscounted post-increment zero index evaluation.',
      question: null as any,
    },
  ];

  // Mastery scores per user and topic
  public masteries: TopicMastery[] = [
    {
      topic: 'Integration by Parts & Partial Fractions',
      subject: 'Higher Mathematics',
      masteryScore: 43,
      accuracyPercentage: 43,
      totalAttempts: 14,
      correctAttempts: 6,
      recentAttempts: [false, false, true, false, false],
      lastPracticedDate: new Date().toISOString(),
      decayedScore: 41,
      status: 'critical',
    },
    {
      topic: 'Kinematics & Projectile Dynamics',
      subject: 'Physics',
      masteryScore: 88,
      accuracyPercentage: 90,
      totalAttempts: 22,
      correctAttempts: 20,
      recentAttempts: [true, true, true, true, true],
      lastPracticedDate: new Date().toISOString(),
      decayedScore: 88,
      status: 'mastered',
    },
    {
      topic: 'Isothermal & Adiabatic Gas Processes',
      subject: 'Physics',
      masteryScore: 74,
      accuracyPercentage: 75,
      totalAttempts: 12,
      correctAttempts: 9,
      recentAttempts: [true, true, false, true, true],
      lastPracticedDate: new Date().toISOString(),
      decayedScore: 74,
      status: 'improving',
    },
    {
      topic: 'Electrophilic Substitution & Benzene',
      subject: 'Chemistry',
      masteryScore: 62,
      accuracyPercentage: 65,
      totalAttempts: 10,
      correctAttempts: 6,
      recentAttempts: [false, true, true, false, true],
      lastPracticedDate: new Date().toISOString(),
      decayedScore: 62,
      status: 'improving',
    },
    {
      topic: 'Mendelian Genetics & Blood Groups',
      subject: 'Biology',
      masteryScore: 85,
      accuracyPercentage: 88,
      totalAttempts: 15,
      correctAttempts: 13,
      recentAttempts: [true, true, true, true, true],
      lastPracticedDate: new Date().toISOString(),
      decayedScore: 85,
      status: 'mastered',
    },
  ];

  // Human-Led Verified Tutors in Bangladesh (populated from approved teacher accounts)
  public tutors: Tutor[] = [];

  // Bookings store
  public bookings: TutorBooking[] = [];

  // Daily Study Plan
  public studyPlan: DailyStudyPlan = {
    id: 'sp_today',
    date: new Date().toISOString().split('T')[0],
    title: "Today's High-Yield Admission Priority Plan",
    totalMinutes: 90,
    completedMinutes: 35,
    focusTopic: 'Integration by Parts & Partial Fractions',
    tasks: [
      {
        id: 'task-1',
        title: 'Integration Fundamentals & LIATE Rule',
        topic: 'Integration by Parts',
        subject: 'Higher Mathematics',
        minutes: 15,
        completed: true,
        priority: 'high',
        type: 'review',
        reason: 'Master the algebraic ordering for integration by parts.',
      },
      {
        id: 'task-2',
        title: 'Rational Polynomial Partial Fraction Drill',
        topic: 'Integration by Parts & Partial Fractions',
        subject: 'Higher Mathematics',
        minutes: 20,
        completed: false,
        priority: 'high',
        type: 'drill',
        reason: 'Targeted remediation for 43% mastery score.',
      },
      {
        id: 'task-3',
        title: 'Physics Thermodynamics & 1st Law Revision',
        topic: 'Isothermal & Adiabatic Gas Processes',
        subject: 'Physics',
        minutes: 25,
        completed: false,
        priority: 'medium',
        type: 'review',
        reason: 'Strengthen adiabatic PV^gamma relationships.',
      },
      {
        id: 'task-4',
        title: 'Timed 10-Question Mini Simulation Test',
        topic: 'Full Model Drill',
        subject: 'Mixed STEM',
        minutes: 30,
        completed: false,
        priority: 'medium',
        type: 'mock',
        reason: 'Test pacing under 1.5 min/question exam speed.',
      },
    ],
  };

  // Content Versioning history
  public contentVersions: ContentVersion[] = [];

  // Audit Logs
  public auditLogs: AuditLog[] = [
    {
      id: 'log_001',
      actorId: 'usr_admin_1',
      actorEmail: 'admin@virtualtutor.bd',
      actorRole: 'ADMIN',
      action: 'CONTENT_PUBLISHED',
      entity: 'Question',
      entityId: '14',
      details: 'Published bilingual Question #14 on Partial Fractions with updated step-by-step.',
      timestamp: '2024-01-15T10:00:00.000Z',
    },
    {
      id: 'log_002',
      actorId: 'usr_admin_1',
      actorEmail: 'admin@virtualtutor.bd',
      actorRole: 'ADMIN',
      action: 'CONTENT_PUBLISHED',
      entity: 'Question',
      entityId: '17',
      details: 'Published Physics Thermodynamics question with First Law proof.',
      timestamp: '2024-01-16T10:00:00.000Z',
    },
  ];

  // Helper method: Get safe questions stripped of correct answers and explanations for active exams
  public getSafeQuestions(questions: Question[]): SafeQuestion[] {
    return questions.map((q) => ({
      id: q.id,
      subjectId: q.subjectId,
      subjectName: q.subjectName,
      chapterName: q.chapterName,
      topicName: q.topicName,
      difficulty: q.difficulty,
      titleEn: q.titleEn,
      titleBn: q.titleBn,
      questionTextEn: q.questionTextEn,
      questionTextBn: q.questionTextBn,
      formula: q.formula,
      graphType: q.graphType,
      options: q.options.map((opt) => ({
        id: opt.id,
        textEn: opt.textEn,
        textBn: opt.textBn,
      })),
      curriculum: q.curriculum,
      board: q.board,
      admissionCategory: q.admissionCategory,
    }));
  }

  // Record an audit event
  public recordAudit(actorId: string, actorEmail: string, actorRole: any, action: string, entity: string, entityId: string, details: string) {
    this.auditLogs.unshift({
      id: `log_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      actorId,
      actorEmail,
      actorRole,
      action,
      entity,
      entityId,
      details,
      timestamp: new Date().toISOString(),
    });
  }
}

export const db = new DatabaseStore();
